# Generated by Django 4.1.7 on 2023-04-02 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz2',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20, verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='Stu2',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=30)),
                ('Clazz2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu2.clazz2')),
            ],
        ),
    ]
